---
title: "Eigenfaces"
output: pdf_document
date: "2025-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(OpenImageR)
library(EBImage)
library(grid)
```


# Data Import and Preprocessing 

```{r}

image_path = "Training/1AT.jpg"
Im = readImage(image_path)
red = Im[,,1]
green = Im[,,2]
blue = Im[,,3]
# 
# data = cbind(as.vector(red),as.vector(green),as.vector(blue))
# 
# read_data = function(nombre){
#   aux_read = readImage(nombre)
#   red_aux = Im[,,1]
#   green_aux = Im[,,2]
#   blue_aux = Im[,,3]
#   data_aux = data.frame(Red = as.vector(red_aux),
#                         Green = as.vector(green_aux),
#                         Blue = as.vector(blue_aux))
#   return(data_aux)
# }
# uno = read_data("Training/1AT.jpg")
# dos = read_data("Training/1BT.jpg")
# head(uno)
# head(dos)
# 
# 
# data = rbind(uno,dos)
```
```{r}
red = Im[,,1]
green=Im[,,2]
blue=Im[,,3]

X = cbind(as.vector(red), as.vector(green), as.vector(blue))

### Helper Functions

column_means = function(X) {
  n = nrow(X)  # Number of rows (observations)
  return(apply(X, 2, sum) / n)  # Sum each column and divide by n
}
```


# PCA

```{r, echo=FALSE, warning=FALSE, message=FALSE}

### PCA
## Calculate Covariance Matrix

n = nrow(X)
mu = column_means(X) 

# center
X_centered = sweep(X, 2, mu, FUN = "-")

# Compute the covariance matrix
cov_matrix = (t(X_centered) %*% X_centered) / (n - 1)
  

## Calculate Eigenvalues and Eigenvectors and sort
eig = eigen(cov_matrix)
eig_val = eig$values
eig_vec = eig$vectors

# sort
sort_index <- order(eig_val, decreasing = TRUE)
eig_val_sorted <- eig_val[sort_index]
eig_vec_sorted <- eig_vec[, sort_index]


## Calculate Principal Components & print
pc1 = X_centered %*% eig_vec_sorted[,1]
pc1_image = matrix(pc1,nrow=nrow(red), ncol=ncol(green))

# show
dev.new()
print(imageShow(pc1_image))
```

```{r}


### Verify with library
out = princomp(X)

pc1 = matrix(out$scores[,1],nrow=nrow(red), ncol=ncol(green))
imageShow(pc1)

pc2 = matrix(out$scores[,2],nrow=nrow(red), ncol=ncol(green))
imageShow(pc2)

pc3 = matrix(out$scores[,3],nrow=nrow(red), ncol=ncol(green))
imageShow(pc3)
```


## KNN



```{r}
# Load Image
load_and_flatten <- function(image_path, target_size = c(100, 100)) {
  img <- readImage(image_path)          
  img <- resize(img, w = target_size[1], h = target_size[2])  # Resize
  img <- channel(img, "gray") # greyscaled       
  img_vector <- as.vector(img)
  return(img_vector)
}

# Load training images
image_paths <- list.files("Training_alpha", full.names = TRUE)
train_data <- t(sapply(image_paths, load_and_flatten))  # each row = flattend image
train_labels <- rep(1, length(image_paths))  # Label all training images as '1' (person's face)

```


### Define KNN Algo
```{r}

### KNN Algo
knn_manual <- function(train_data, train_labels, test_data, k, threshold) {
  predictions <- c()
  
  # TODO: k <= n_images
  
  for (i in 1:nrow(test_data)) {
    distances <- as.matrix(dist(rbind(test_data[i, ], train_data)))[1, -1]
    k_neighbors <- order(distances)[1:k]
    neighbor_labels <- train_labels[k_neighbors] # get labels of neighbors
    predicted_label <- names(sort(table(neighbor_labels), decreasing = TRUE))[1] # make frequency table and pick most frequent 
    
    # Check treshhold for class 0
    avg_distance <- mean(distances[k_neighbors])

    if (avg_distance > threshold) {
      predicted_label <- "0"
    } else {
      # Majority vote among k neighbors
      predicted_label <- names(sort(table(neighbor_labels), decreasing = TRUE))[1]
    }
    
    predictions <- c(predictions, predicted_label)
  }
  
  return(predictions)
}

#debug(knn_manual)


### Set threshold for valid classification
estimate_threshold_percentile <- function(train_data, train_labels, percentile = 0.90) {
  class_1 <- train_data[train_labels == 1, , drop = FALSE]
  dist_1 <- as.matrix(dist(class_1))
  
  # Extract upper triangle distances
  threshold <- quantile(dist_1[upper.tri(dist_1)], percentile)

  return(threshold)
}


```


```{r}
test_image <- load_and_flatten("Test_alpha/20BT.jpg")  # Load & flatten test image
test_data <- matrix(test_image, nrow = 1)  # Ensure test data format


# Compute threshold
threshold <- estimate_threshold_percentile(train_data, train_labels,percentile= 0.90)
print(threshold)

k <- 4  # Choose k value
prediction <- knn_manual(train_data, train_labels, test_data, k,threshold=threshold)

print(paste("Person_ID:", prediction))

```


## Apply funcionts

raw_data -> KNN
raw_data -> PCA -> KNN
raw_data -> PCA -> DiscrAnal -> KNN














